/*
 * DASHBOARD_System_Clock_Config.h
 *
 *  Created on: Mar 17, 2024
 *      Author: Sigma
 */

#ifndef APP_DASHBOARD_SYSTEM_CLOCK_DASHBOARD_SYSTEM_CLOCK_CONFIG_H_
#define APP_DASHBOARD_SYSTEM_CLOCK_DASHBOARD_SYSTEM_CLOCK_CONFIG_H_

#define TICK_TIME_1SEC  1000
#define MAX_INACTIVE_TIME 20
#define REALY_ALARM_TIME_IN_SECS 2
#define SECS_INITIAL_TIME 0
#define MINS_INITIAL_TIME 35
#define HOURS_INITIAL_TIME 10
#define LOAD_VARIABLES_TIME 5
#endif /* APP_DASHBOARD_SYSTEM_CLOCK_DASHBOARD_SYSTEM_CLOCK_CONFIG_H_ */
