/*
 * DRIV_MONITORING_CONFIG.h
 *
 * Created: 3/17/2024 9:22:33 PM
 *  Author: seif
 */ 


#ifndef DRIV_MONITORING_CONFIG_H_
#define DRIV_MONITORING_CONFIG_H_

#define DRIV_MONITORING_ON 1
#define DRIV_MONITORING_OFF 0



#endif /* DRIV_MONITORING_CONFIG_H_ */