/*
 * APP_CONFIG.h
 *
 * Created: 3/16/2024 1:31:11 PM
 *  Author: seif
 */ 


#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

#define N_STATE 0
#define D_STATE 1
#define R_STATE 2

#define GEAR_LCD_STATUS_N GEAR_STATUS_DISPLAY[N_STATE]	
#define GEAR_LCD_STATUS_D GEAR_STATUS_DISPLAY[D_STATE] 
#define GEAR_LCD_STATUS_R GEAR_STATUS_DISPLAY[R_STATE]

#define CRUISE_LCD_STATUS_OFF CRUISE_STATUS_DISPLAY[0] 
#define CRUISE_LCD_STATUS_ON CRUISE_STATUS_DISPLAY[1] 
#define CRUISE_BUTTON_STATUS_OFF 1 
#define CRUISE_BUTTON_STATUS_ON 0
#define BA_LCD_STATUS_OFF BRAKE_ASSIST_STATUS_DISPLAY[0]
#define BA_LCD_STATUS_ON BRAKE_ASSIST_STATUS_DISPLAY[1] 
#define BA_BUTTON_STATUS_OFF 1
#define BA_BUTTON_STATUS_ON 0
#define SL_LCD_STATUS_OFF SPEED_LIMIT_STATUS_DISPLAY[0]
#define SL_LCD_STATUS_ON SPEED_LIMIT_STATUS_DISPLAY[1]  

#define DM_LCD_STATUS_OFF DRIVER_MONITORING_STATUS_DISPLAY[0]
#define DM_LCD_STATUS_ON DRIVER_MONITORING_STATUS_DISPLAY[1]

#define LCD_SCREEN1 0
#define LCD_SCREEN2 1
#define LCD_SCREEN3 2 
#define LCD_SCREEN4 4
#define right 1
#define left 0
#define BRAKE_ON 1
#define BRAKE_OFF 0

#define BRAKE_ASSIST_KEYPAD_PRESSED '1'
#define BRAKE_KEYPAD_PRESSED '2'
#define CRUISE_KEYPAD_PRESSED '3'
#define LCD_LEFT_SCROLL_KEYPAD_PRESSED '5'
#define LCD_RIGHT_SCROLL_KEYPAD_PRESSED '6'
#define SPEED_LIMIT_STATE_KEYPAD_PRESSED '7'

#define WARNING_DISPLAY "WARNING!!!!"
#endif /* APP_CONFIG_H_ */
